# Makefile for the Beamformation toolbox
# Ver 1.0
# O5 Sep. 2000, Svetoslav Nikolov
# In order to make some target, include the corresponding file

include Makefile.Linux

#Example to make for win64
# mex -O -output bft.mexw64 -LC:\Users\AlexS\Documents\MATLAB\bft_64bit\c -lpthreadVC2 c/mex_beamform.c c/focus.c c/beamform.c c/geometry.c c/transducer.c c/motion.c -DMX_COMPAT_32 -D__MSCVC_ -IC:\Users\AlexS\Documents\MATLAB\bft_64bit\c